# Optimization Homework 01 Notebook

In [12]:
import itertools
import numpy as np

## Define Functions

In [26]:
def all_sparse_solutions(A, b, print_solutions=False):
    A = np.asarray(A)
    b = np.asarray(b)

    m, n = A.shape
    assert b.shape[0] == m, "b must have length m."

    solutions = []

    # Try all subsets S of size m (non-zero indices)
    for S in itertools.combinations(range(n), m):
        S = list(S)
        A_S = A[:, S]   # m×m submatrix

        # Check if A_S is invertible (independent columns)
        if np.linalg.matrix_rank(A_S) < m:
            continue  # no unique solution for this support

        # Solve A_S x_S = b
        try:
            x_S = np.linalg.solve(A_S, b)
        except np.linalg.LinAlgError:
            continue

        # Build full x vector
        x = np.zeros(n)
        x[S] = x_S

        # Verify numerically (to avoid floating point issues)
        if np.allclose(A @ x, b):
            solutions.append(x)

    # Reverse the order of solutions
    solutions = solutions[::-1]

    if print_solutions:
        for sol in solutions:
            print(sol)

    return solutions

def print_objective_values(solutions, c):
    c = np.asarray(c)
    
    print("\n=== Objective values ===")
    for sol in solutions:
        feasible = True
        for s in sol:
            if s < 0:
                print("-")
                feasible = False
                break
        if feasible:
            print(sol @ c)  

---

## Problem 2

In [33]:
# Problem 2.a.

A = np.array([
    [3, 2, 1, 0],
    [1, 2, 0, 1],
])

b = np.array([6, 4]).transpose()

solutions = all_sparse_solutions(A, b, print_solutions=True)
print_objective_values(solutions, c=[1, 1, 0, 0])

[0. 0. 6. 4.]
[ 0.  3.  0. -2.]
[0. 2. 2. 0.]
[2. 0. 0. 2.]
[ 4.  0. -6.  0.]
[1.  1.5 0.  0. ]

=== Objective values ===
0.0
-
2.0
2.0
-
2.5


In [34]:
# Problem 2.b.

A = np.array([
    [3, 2, 1, 0],
    [1, 2, 0, 1],
])

b = np.array([6, 4]).transpose()

solutions = all_sparse_solutions(A, b, print_solutions=True)
print_objective_values(solutions, c=[0.5, 1, 0, 0])

[0. 0. 6. 4.]
[ 0.  3.  0. -2.]
[0. 2. 2. 0.]
[2. 0. 0. 2.]
[ 4.  0. -6.  0.]
[1.  1.5 0.  0. ]

=== Objective values ===
0.0
-
2.0
1.0
-
2.0


## Problem 3

In [29]:
# Problem 3

A = np.array([
    [1, 1, 1, 0, 0],
    [1, 3, 0, 1, 0],
    [2, -1, 0, 0, -1]
])

b = np.array([3, 4, 1]).transpose()

solutions = all_sparse_solutions(A, b, print_solutions=True)
print_objective_values(solutions, c=[1, -1, 0, 0, 0])

[ 0.  0.  3.  4. -1.]
[ 0.  3.  0. -5. -4.]
[ 0.          1.33333333  1.66666667  0.         -2.33333333]
[ 0. -1.  4.  7.  0.]
[3. 0. 0. 1. 5.]
[ 4.  0. -1.  0.  7.]
[0.5 0.  2.5 3.5 0. ]
[2.5 0.5 0.  0.  3.5]
[ 1.33333333  1.66666667  0.         -2.33333333  0.        ]
[1. 1. 1. 0. 0.]

=== Objective values ===
-
-
-
-
3.0
-
0.5
2.0
-
0.0


## Problem 4

In [31]:
# Problem 4

A = np.array([
    [2, 6, 8, 0, 0],
    [1, -1, 0, -1, 0],
    [0, 1, -1, 0, -1]
])

b = np.array([60, 2, 1]).transpose()

solutions = all_sparse_solutions(A, b, print_solutions=True)
print_objective_values(solutions, c=[-1, -2, -3, 0, 0])

[ 0.   0.   7.5 -2.  -8.5]
[  0.  10.   0. -12.   9.]
[  0.  -2.   9.   0. -12.]
[ 0.          4.85714286  3.85714286 -6.85714286  0.        ]
[30.  0.  0. 28. -1.]
[ 2.  0.  7.  0. -8.]
[34.  0. -1. 32.  0.]
[9. 7. 0. 0. 6.]
[27.  1.  0. 24.  0.]
[6. 4. 3. 0. 0.]

=== Objective values ===
-
-
-
-
-
-
-
-23.0
-29.0
-23.0


---